### ISSUE TITLE
Unable to create a drawing

### ISSUE THREAD

**Issue by arn314** [jsventures/instldraw#3]
I followed the instructions in Readme to try and run this example app. I was able to sign-in, create a team but I'm unable to create a drawing. I repeatedly get below error:
```
{
    "status": "error",
    "clientId": "7b4d8391-b9c5-4a72-bbf6-75a75a9b1d1f",
    "message": "Record not unique: ident",
    "hint": {
        "record-type": "ident"
    }
}
```
How do I resolve / debug this?

**Comment by ryanrussell** [comment]
+1

For some additional context, it's `onsubmit() on index.tsx:269` which calls 

`const response = await createDrawingForTeam({`

There are memberships and teams tables, but it does not seem to instantiate the drawings table.

**Comment by ryanrussell** [comment]
Was fixed by https://github.com/instantdb/instant/commit/32acb2897176c8d766def46e615d65ea054ea8f4

Working now. Thanks @dwwoelfel

Would suggest closing.
